import Link from "next/link";
import "../globals.css";
import Image from "next/image";

export const metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en" className={`h-full relative`}>
      <body className="min-h-full flex flex-col relative">
        <header className="w-full relative z-10 overflow-x-hidden">
          <nav className="w-full border-b border-[#10B77F1A] h-16.25 flex items-center justify-between px-4 md:px-8 lg:px-10">
            <Link href={"/"}>
              <Image
                src={"/logo.svg"}
                width={96}
                height={32}
                alt="Uptrix logo"
              />
            </Link>

            <div className="flex items-center gap-x-5 gap-y-2">
              <p className="text-[#F1F5F9] text-sm font-medium">Help Center</p>
              <p className="text-[#F1F5F9] text-sm font-medium">
                Privacy Policy
              </p>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
