import Link from "next/link";
import "../globals.css";
import Image from "next/image";

export const metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en" className={`h-full relative`}>
      <body className="min-h-full flex flex-col">
        <header className="w-full relative">
          <nav className="w-full border-b border-[#10B77F1A] h-16.25 flex items-center justify-between px-4 md:px-8 lg:px-10">
            <Link href={"/"}>
              <Image
                src={"/logo.svg"}
                width={96}
                height={32}
                alt="Uptrix logo"
              />
            </Link>

            <p className="text-sm leading-5 secondary-text">
              Join the next generation of builders
            </p>
          </nav>
        </header>
        {children}

        <footer className="w-full pt-5 pb-10 text-center">
          <p className="text-(--gray) text-xs">
            © 2024 Uptrix Inc. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
