import Navbar from "@/layout/Navbar";
import "../globals.css";
import Footer from "@/layout/Footer";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="en" className={`h-full relative`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <>
            <Navbar />
            {children} <Footer />
          </>
        </AuthProvider>
      </body>
    </html>
  );
}
