import "../globals.css";

export const metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en" className={`h-full relative`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
