import Link from "next/link";
import "../globals.css";
import Image from "next/image";

export const metadata = {
  title: "Auth Page",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en" className={`h-full relative`}>
      <body className="min-h-full flex flex-col">
        <header className="w-full relative">
          <nav className="w-full border-b border-[#10B77F1A] h-18.25 flex items-center justify-between px-4 md:px-8 lg:px-10">
            <Link href={"/"}>
              <Image
                src={"/uptrix-logo.svg"}
                width={100}
                height={32}
                alt="Uptrix logo"
              />
            </Link>

            <button type="button">
              <Image
                src={"/cancel-button.svg"}
                alt="cancel-button"
                width={40}
                height={40}
              />
            </button>
          </nav>
        </header>
        {children}

        <footer className="w-full pt-5 pb-10 text-center">
          <p className="text-(--gray) text-xs">
            © 2024 Uptrix Identity Solutions. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
